const districts_up = [
    { "value": "Agra", "label": "Agra" },
    { "value": "Aligarh", "label": "Aligarh" },
    { "value": "Prayagraj", "label": "Prayagraj" },
    { "value": "Ambedkar Nagar", "label": "Ambedkar Nagar" },
    { "value": "Auraiya", "label": "Auraiya" },
    { "value": "Azamgarh", "label": "Azamgarh" },
    { "value": "Bagpat", "label": "Bagpat" },
    { "value": "Bahraich", "label": "Bahraich" },
    { "value": "Ballia", "label": "Ballia" },
    { "value": "Balrampur", "label": "Balrampur" },
    { "value": "Banda", "label": "Banda" },
    { "value": "Barabanki", "label": "Barabanki" },
    { "value": "Bareilly", "label": "Bareilly" },
    { "value": "Basti", "label": "Basti" },
    { "value": "Bijnor", "label": "Bijnor" },
    { "value": "Budaun", "label": "Budaun" },
    { "value": "Bulandshahr", "label": "Bulandshahr" },
    { "value": "Chandauli", "label": "Chandauli" },
    { "value": "Chitrakoot", "label": "Chitrakoot" },
    { "value": "Deoria", "label": "Deoria" },
    { "value": "Etah", "label": "Etah" },
    { "value": "Etawah", "label": "Etawah" },
    { "value": "Faizabad", "label": "Faizabad" },
    { "value": "Farrukhabad", "label": "Farrukhabad" },
    { "value": "Fatehpur", "label": "Fatehpur" },
    { "value": "Firozabad", "label": "Firozabad" },
    { "value": "Gautam Buddha Nagar", "label": "Gautam Buddha Nagar" },
    { "value": "Ghaziabad", "label": "Ghaziabad" },
    { "value": "Gonda", "label": "Gonda" },
    { "value": "Gorakhpur", "label": "Gorakhpur" },
    { "value": "Hamirpur", "label": "Hamirpur" },
    { "value": "Hapur", "label": "Hapur" },
    { "value": "Hardoi", "label": "Hardoi" },
    { "value": "Hathras", "label": "Hathras" },
    { "value": "Jalaun", "label": "Jalaun" },
    { "value": "Jaunpur", "label": "Jaunpur" },
    { "value": "Jhansi", "label": "Jhansi" },
    { "value": "Kannauj", "label": "Kannauj" },
    { "value": "Kanpur Dehat", "label": "Kanpur Dehat" },
    { "value": "Kanpur Nagar", "label": "Kanpur Nagar" },
    { "value": "Kushinagar", "label": "Kushinagar" },
    { "value": "Lakhimpur Kheri", "label": "Lakhimpur Kheri" },
    { "value": "Lalitpur", "label": "Lalitpur" },
    { "value": "Lucknow", "label": "Lucknow" },
    { "value": "Maharajganj", "label": "Maharajganj" },
    { "value": "Mahoba", "label": "Mahoba" },
    { "value": "Mainpuri", "label": "Mainpuri" },
    { "value": "Mathura", "label": "Mathura" },
    { "value": "Meerut", "label": "Meerut" },
    { "value": "Mirzapur", "label": "Mirzapur" },
    { "value": "Moradabad", "label": "Moradabad" },
    { "value": "Muzaffarnagar", "label": "Muzaffarnagar" },
    { "value": "Pilibhit", "label": "Pilibhit" },
    { "value": "Pratapgarh", "label": "Pratapgarh" },
    { "value": "Raebareli", "label": "Raebareli" },
    { "value": "Rampur", "label": "Rampur" },
    { "value": "Saharanpur", "label": "Saharanpur" },
    { "value": "Sant Kabir Nagar", "label": "Sant Kabir Nagar" },
    { "value": "Shahjahanpur", "label": "Shahjahanpur" },
    { "value": "Shamli", "label": "Shamli" },
    { "value": "Shravasti", "label": "Shravasti" },
    { "value": "Siddharthnagar", "label": "Siddharthnagar" },
    { "value": "Sitapur", "label": "Sitapur" },
    { "value": "Sonbhadra", "label": "Sonbhadra" },
    { "value": "Sultanpur", "label": "Sultanpur" },
    { "value": "Unnao", "label": "Unnao" },
    { "value": "Varanasi", "label": "Varanasi" }
];



const IND_state = [
    { "value": "Andhra Pradesh", "label": "Andhra Pradesh" },
    { "value": "Arunachal Pradesh", "label": "Arunachal Pradesh" },
    { "value": "Assam", "label": "Assam" },
    { "value": "Bihar", "label": "Bihar" },
    { "value": "Chhattisgarh", "label": "Chhattisgarh" },
    { "value": "Goa", "label": "Goa" },
    { "value": "Gujarat", "label": "Gujarat" },
    { "value": "Haryana", "label": "Haryana" },
    { "value": "Himachal Pradesh", "label": "Himachal Pradesh" },
    { "value": "Jammu and Kashmir", "label": "Jammu and Kashmir" },
    { "value": "Jharkhand", "label": "Jharkhand" },
    { "value": "Karnataka", "label": "Karnataka" },
    { "value": "Kerala", "label": "Kerala" },
    { "value": "Madhya Pradesh", "label": "Madhya Pradesh" },
    { "value": "Maharashtra", "label": "Maharashtra" },
    { "value": "Manipur", "label": "Manipur" },
    { "value": "Meghalaya", "label": "Meghalaya" },
    { "value": "Mizoram", "label": "Mizoram" },
    { "value": "Nagaland", "label": "Nagaland" },
    { "value": "Odisha", "label": "Odisha" },
    { "value": "Punjab", "label": "Punjab" },
    { "value": "Rajasthan", "label": "Rajasthan" },
    { "value": "Sikkim", "label": "Sikkim" },
    { "value": "Tamil Nadu", "label": "Tamil Nadu" },
    { "value": "Telangana", "label": "Telangana" },
    { "value": "Tripura", "label": "Tripura" },
    { "value": "Uttar Pradesh", "label": "Uttar Pradesh" },
    { "value": "Uttarakhand", "label": "Uttarakhand" },
    { "value": "West Bengal", "label": "West Bengal" }
]


export { districts_up, IND_state }